on:
  push:
     branches:
          - master
    




jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          

          - uses: actions/checkout@v3
          - name: "login to docker hub"
            run: docker login --username ${{ secrets.docker_username }} --password ${{ secrets.docker_password }} 
          -  name: "Docker image build "
             run: docker build -t ${{ secrets.docker_username }}/image_tast .
          -  name: "push to docker hub"
             run: docker push ${{ secrets.docker_username }}/image_tast
